// Логіка карток Шанс для Монополії - 100 карток

const chanceCards = [
    { message: "Ви виграли лотерею! Отримуєте 200.", effect: player => player.balance += 200 },
    { message: "Сплатіть штраф за перевищення швидкості: 150.", effect: player => player.balance -= 150 },
    { message: "Отримайте бонус за успішну інвестицію: 300.", effect: player => player.balance += 300 },
    { message: "Ви втратили гаманець! Втрата: 100.", effect: player => player.balance -= 100 },
    { message: "Вас запросили на благодійність. Сплачуєте 50.", effect: player => player.balance -= 50 },
    { message: "Отримуєте спадок від далекого родича: 500.", effect: player => player.balance += 500 },
    { message: "Ваш автомобіль зламався. Сплачуєте ремонт: 200.", effect: player => player.balance -= 200 },
    { message: "Знайдено скарб! Отримуєте 400.", effect: player => player.balance += 400 },
    { message: "Вас пограбували. Втрата: 300.", effect: player => player.balance -= 300 },
    { message: "Отримали бонус на роботі: 100.", effect: player => player.balance += 100 },
    { message: "Сплачуєте штраф за парковку в недозволеному місці: 75.", effect: player => player.balance -= 75 },
    { message: "Отримали податкове відшкодування: 250.", effect: player => player.balance += 250 },
    { message: "Ви виграли спортивне змагання! Отримуєте 150.", effect: player => player.balance += 150 },
    { message: "Вам виписано штраф за порушення правил: 100.", effect: player => player.balance -= 100 },
    { message: "Отримали премію від роботодавця: 200.", effect: player => player.balance += 200 },
    { message: "Ваш бізнес приніс прибуток! Отримуєте 350.", effect: player => player.balance += 350 },
    { message: "Ви втратили кошти через шахрайство. Втрата: 150.", effect: player => player.balance -= 150 },
    { message: "Отримали подарунок від друга: 100.", effect: player => player.balance += 100 },
    { message: "Вам виписано штраф за сміття на вулиці: 50.", effect: player => player.balance -= 50 },
    { message: "Отримали компенсацію за страхування: 300.", effect: player => player.balance += 300 },
    { message: "Заплатили за ремонт будинку: 250.", effect: player => player.balance -= 250 },
    { message: "Отримали гроші за продаж акцій: 400.", effect: player => player.balance += 400 },
    { message: "Ваш гаманець було вкрадено. Втрата: 100.", effect: player => player.balance -= 100 },
    { message: "Отримали дивіденди за акції: 200.", effect: player => player.balance += 200 },
    { message: "Сплатили медичні витрати: 150.", effect: player => player.balance -= 150 },
    { message: "Отримали виграш у вікторині: 100.", effect: player => player.balance += 100 },
    { message: "Сплатили за страховий поліс: 120.", effect: player => player.balance -= 120 },
    { message: "Отримали спадок: 300.", effect: player => player.balance += 300 },
    { message: "Вас оштрафували за неправильну парковку: 80.", effect: player => player.balance -= 80 },
    { message: "Отримали грант на навчання: 200.", effect: player => player.balance += 200 },
    { message: "Сплатили рахунки за комунальні послуги: 100.", effect: player => player.balance -= 100 },
    { message: "Отримали подарунковий сертифікат: 150.", effect: player => player.balance += 150 },
    { message: "Ваша нерухомість знецінилася. Втрата: 200.", effect: player => player.balance -= 200 },
    { message: "Отримали компенсацію за затримку рейсу: 100.", effect: player => player.balance += 100 },
    { message: "Сплатили податок на нерухомість: 180.", effect: player => player.balance -= 180 },
    { message: "Отримали бонус за гарні результати роботи: 250.", effect: player => player.balance += 250 },
    { message: "Сплатили штраф за порушення правил дорожнього руху: 200.", effect: player => player.balance -= 200 },
    { message: "Отримали виграш у казино: 300.", effect: player => player.balance += 300 },
    { message: "Ви втратили цінні папери. Втрата: 150.", effect: player => player.balance -= 150 },
    { message: "Отримали прибуток від оренди нерухомості: 350.", effect: player => player.balance += 350 },
    { message: "Сплатили за обслуговування автомобіля: 120.", effect: player => player.balance -= 120 },
    { message: "Отримали повернення податків: 400.", effect: player => player.balance += 400 },
    { message: "Ваш банк нарахував комісію. Втрата: 50.", effect: player => player.balance -= 50 },
    { message: "Отримали гроші за роботу фрілансера: 180.", effect: player => player.balance += 180 },
    { message: "Сплатили штраф за порушення громадського порядку: 70.", effect: player => player.balance -= 70 },
    { message: "Отримали бонус за участь у конференції: 150.", effect: player => player.balance += 150 },
    { message: "Ваш рахунок було заблоковано. Втрата: 100.", effect: player => player.balance -= 100 },
    { message: "Отримали гроші за продаж автомобіля: 500.", effect: player => player.balance += 500 },
    { message: "Сплатили за навчальні курси: 130.", effect: player => player.balance -= 130 },
    { message: "Отримали виграш у розіграші: 200.", effect: player => player.balance += 200 },
    { message: "Ваш будинок потребує ремонту. Сплатили: 220.", effect: player => player.balance -= 220 },
    { message: "Отримали гроші за надання консультацій: 300.", effect: player => player.balance += 300 },
    { message: "Сплатили за ліки: 90.", effect: player => player.balance -= 90 },
    { message: "Отримали гроші за здачу металобрухту: 50.", effect: player => player.balance += 50 },
    { message: "Сплатили за страхування майна: 110.", effect: player => player.balance -= 110 },
    { message: "Отримали дивіденди від акцій: 250.", effect: player => player.balance += 250 },
    { message: "Ваш бізнес зазнав збитків. Втрата: 300.", effect: player => player.balance -= 300 },
    { message: "Отримали гроші за участь у телешоу: 400.", effect: player => player.balance += 400 },
    { message: "Сплатили штраф за шум у громадському місці: 60.", effect: player => player.balance -= 60 },
    { message: "Отримали премію за волонтерську роботу: 100.", effect: player => player.balance += 100 },
    { message: "Ваш банк нарахував відсотки: 150.", effect: player => player.balance += 150 },
    { message: "Сплатили за ремонт сантехніки: 80.", effect: player => player.balance -= 80 },
    { message: "Отримали гроші за викладацьку діяльність: 200.", effect: player => player.balance += 200 },
    { message: "Вашу машину вкрали. Втрата: 400.", effect: player => player.balance -= 400 },
    { message: "Отримали виграш у благодійному лотереї: 300.", effect: player => player.balance += 300 },
    { message: "Сплатили за послуги адвоката: 200.", effect: player => player.balance -= 200 },
    { message: "Отримали гроші за ремонт техніки: 150.", effect: player => player.balance += 150 },
    { message: "Ваш будинок було пошкоджено. Втрата: 250.", effect: player => player.balance -= 250 },
    { message: "Отримали гроші за продаж меблів: 180.", effect: player => player.balance += 180 },
    { message: "Сплатили за послуги дизайнера: 130.", effect: player => player.balance -= 130 },
    { message: "Отримали компенсацію за несправний товар: 90.", effect: player => player.balance += 90 },
    { message: "Вашу квартиру затопило. Втрата: 300.", effect: player => player.balance -= 300 },
    { message: "Отримали гроші за оренду авто: 200.", effect: player => player.balance += 200 },
    { message: "Сплатили за новий паспорт: 50.", effect: player => player.balance -= 50 },
    { message: "Отримали бонус за святкування: 100.", effect: player => player.balance += 100 },
    { message: "Ваші інвестиції не вдалися. Втрата: 350.", effect: player => player.balance -= 350 },
    { message: "Отримали виграш у лотереї: 500.", effect: player => player.balance += 500 },
    { message: "Сплатили за технічне обслуговування: 150.", effect: player => player.balance -= 150 },
    { message: "Отримали компенсацію за втрату багажу: 250.", effect: player => player.balance += 250 },
    { message: "Ваш автомобіль потрапив у ДТП. Втрата: 300.", effect: player => player.balance -= 300 },
    { message: "Отримали гроші за зйомку реклами: 350.", effect: player => player.balance += 350 },
    { message: "Сплатили за послуги електрика: 100.", effect: player => player.balance -= 100 },
    { message: "Отримали гроші за продаж старих речей: 150.", effect: player => player.balance += 150 },
    { message: "Ваш рахунок було заблоковано. Втрата: 200.", effect: player => player.balance -= 200 }
  ];
  
  // Експорт карток для використання в інших файлах
  export default chanceCards;
  